### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by Tarhyru** [zhangkaiyulw/scaffold-kit#7]
我尝试按照文档指引运行
I tried to follow the documentation
到这一步的时候
At this point

>“Now link the blog scaffold tool we've just created into our command line.”

我发现,package.json中的bin和目录中不一致
I found that the bin in package.json is inconsistent with the bin in the directory
```js
  "bin": {
    "test-generator": "lib/testGenerator.js"
  },
```
实际上的路径是:"lib/startup.js" 
The actual path is "lib/startup.js"

**Comment by Tarhyru** [comment]
即使我修改了路径,让它能成功连接...
Even if I change the path so that it connects successfully...

运行的时候也会报错，连接后它无法通过相对路径找到package.json
Running time will also be an error, after the connection it can not be found through the relative path

>"line 1: /node_modules/test-generator/lib/app.js: No such file or directory"

我的操作系统是win10 64位 node版本 10.14.6
My operating system is win10 64-bit node version 10.14.6

**Comment by Tarhyru** [comment]
关于 “Behaviorals” 的一点疑问..它看起来是一条“线”...
At the question of "Behaviorals"... It looks like a "line"...

假设我有  a b c三个功能，会公用修改某个文件...我该怎么组织才能任意保留一个或两个功能？
Suppose I have a, b, and c functions that modify a common file... How do I organize so that I can have one or two functions at will?

我能想到的似乎是写一套操作文件或者对比文件的方法...
All I can think of seems to be a way to write a set of operation files or compare files...

同理，假如我脚手架的原型项目有所更新..怎么快速的更新所有基于该原型的其它由脚手架生成的项目的公用部分...方法似乎和上面一样...
Similarly, if my scaffolding prototype project is updated... How to quickly update common parts of all other scaffolding generated projects based on this prototype... The method seems to be the same as above...

如果参考那个更新文件的列子..想实现上面的功能感觉有些过于复杂...且死板..
If you refer to the example that updates the file.. It feels a little too complicated to implement the above functionality... And rigid..

那个更新感觉是固定的...关于这一块有没有什么想法？
That update feels fixed... Any thoughts on this?

**Comment by zhangkaiyulw** [comment]
Hi @Tarhyru , I cannot reproduce this bug. I think your strange bug is due to some setup on your node.js environment. Please create an issue for each problem you encountered.

**Comment by zhangkaiyulw** [comment]
Hi @Tarhyru , scaffold-kit does not support node <= 8.0
Seems your node version is less than 8.0

**Comment by Tarhyru** [comment]
@zhangkaiyulw 
我觉得应该不是版本问题...我用的nodejs版本为 10.14.6 不是1.14.6...
I don't think it's the version... The nodejs version I used was 10.14.6, not 1.14.6...

这更像是windows下的表现问题,你有尝试在windows 10下按着教程走么..?
This is more of a Windows performance issue. Have you tried following the tutorial in Windows 10?

**Comment by zhangkaiyulw** [comment]
Hi @Tarhyru, thanks for your patient. 
Can you run `scaffold-kit --version` and paste the result here?
Also, try `npm install -g scaffold-kit-cli@1.0` and if errors occured, can you paste error message here?

**Comment by Tarhyru** [comment]
@zhangkaiyulw 
关于输出，全局安装没有问题...
Global installation has no problem with the output...

具体的输出：
Specific output:
```sh
$ scaffold-kit --version
1.0.0
```
另一个问题也许在于在windows下，即使全局安装了"scaffold-kit-cli"在全局里依旧找不到"scaffold-kit"..
Another problem may be that in Windows, even with the "scaffold kit-cli" installed globally, the "scaffold kit" cannot be found in the global context.

**Comment by zhangkaiyulw** [comment]
Hi @Tarhyru ,
Scaffold Kit is not installed globally, the global thing you installed is `scaffold-kit-cli`. The CLI install `scaffold-kit` for you into your local node_modules.

**Comment by zhangkaiyulw** [comment]
Hi @Tarhyru , see my screenshots, I don't have any issue you mentioned.
<img width="1222" alt="Screen Shot 2019-04-16 at 3 08 14 PM" src="https://user-images.githubusercontent.com/3055936/56189008-81599b80-6059-11e9-818e-b0e6ff2a154b.png">
